# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway_agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gateway_agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gateway_agent.proto\x12\x1dkeyhan.gateway_agent_messages\"v\n\x0fLiveLogsRequest\x12\x34\n\x04type\x18\x01 \x01(\x0e\x32&.keyhan.gateway_agent_messages.LogType\x12\x19\n\x11traffic_log_index\x18\x02 \x01(\t\x12\x12\n\nline_count\x18\x03 \x01(\r\"\x1f\n\x10LiveLogsResponse\x12\x0b\n\x03log\x18\x01 \x01(\t\" \n\x0eUptimeResponse\x12\x0e\n\x06uptime\x18\x01 \x01(\t\"%\n\x10\x43puUsageResponse\x12\x11\n\tcpu_usage\x18\x01 \x01(\t\"+\n\x13MemoryUsageResponse\x12\x14\n\x0cmemory_usage\x18\x01 \x01(\t\"\r\n\x0bNullRequest\"\x0e\n\x0cNullResponse*9\n\x07LogType\x12\x0e\n\nCONTROLLER\x10\x00\x12\x0b\n\x07SETTING\x10\x01\x12\x11\n\rGATEWAY_AGENT\x10\x02\x32\xc6\x03\n\x0cGatewayAgent\x12\x65\n\x06Uptime\x12*.keyhan.gateway_agent_messages.NullRequest\x1a-.keyhan.gateway_agent_messages.UptimeResponse\"\x00\x12i\n\x08\x43puUsage\x12*.keyhan.gateway_agent_messages.NullRequest\x1a/.keyhan.gateway_agent_messages.CpuUsageResponse\"\x00\x12o\n\x0bMemoryUsage\x12*.keyhan.gateway_agent_messages.NullRequest\x1a\x32.keyhan.gateway_agent_messages.MemoryUsageResponse\"\x00\x12s\n\x0cReadLiveLogs\x12..keyhan.gateway_agent_messages.LiveLogsRequest\x1a/.keyhan.gateway_agent_messages.LiveLogsResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGTYPE']._serialized_start=356
  _globals['_LOGTYPE']._serialized_end=413
  _globals['_LIVELOGSREQUEST']._serialized_start=54
  _globals['_LIVELOGSREQUEST']._serialized_end=172
  _globals['_LIVELOGSRESPONSE']._serialized_start=174
  _globals['_LIVELOGSRESPONSE']._serialized_end=205
  _globals['_UPTIMERESPONSE']._serialized_start=207
  _globals['_UPTIMERESPONSE']._serialized_end=239
  _globals['_CPUUSAGERESPONSE']._serialized_start=241
  _globals['_CPUUSAGERESPONSE']._serialized_end=278
  _globals['_MEMORYUSAGERESPONSE']._serialized_start=280
  _globals['_MEMORYUSAGERESPONSE']._serialized_end=323
  _globals['_NULLREQUEST']._serialized_start=325
  _globals['_NULLREQUEST']._serialized_end=338
  _globals['_NULLRESPONSE']._serialized_start=340
  _globals['_NULLRESPONSE']._serialized_end=354
  _globals['_GATEWAYAGENT']._serialized_start=416
  _globals['_GATEWAYAGENT']._serialized_end=870
# @@protoc_insertion_point(module_scope)
