# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import backend.gateway_manager.protobuf.gateway_agent_pb2 as gateway__agent__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gateway_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Uptime = channel.unary_unary(
                '/keyhan.gateway_agent_messages.GatewayAgent/Uptime',
                request_serializer=gateway__agent__pb2.NullRequest.SerializeToString,
                response_deserializer=gateway__agent__pb2.UptimeResponse.FromString,
                _registered_method=True)
        self.CpuUsage = channel.unary_unary(
                '/keyhan.gateway_agent_messages.GatewayAgent/CpuUsage',
                request_serializer=gateway__agent__pb2.NullRequest.SerializeToString,
                response_deserializer=gateway__agent__pb2.CpuUsageResponse.FromString,
                _registered_method=True)
        self.MemoryUsage = channel.unary_unary(
                '/keyhan.gateway_agent_messages.GatewayAgent/MemoryUsage',
                request_serializer=gateway__agent__pb2.NullRequest.SerializeToString,
                response_deserializer=gateway__agent__pb2.MemoryUsageResponse.FromString,
                _registered_method=True)
        self.ReadLiveLogs = channel.unary_stream(
                '/keyhan.gateway_agent_messages.GatewayAgent/ReadLiveLogs',
                request_serializer=gateway__agent__pb2.LiveLogsRequest.SerializeToString,
                response_deserializer=gateway__agent__pb2.LiveLogsResponse.FromString,
                _registered_method=True)


class GatewayAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Uptime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CpuUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MemoryUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadLiveLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Uptime': grpc.unary_unary_rpc_method_handler(
                    servicer.Uptime,
                    request_deserializer=gateway__agent__pb2.NullRequest.FromString,
                    response_serializer=gateway__agent__pb2.UptimeResponse.SerializeToString,
            ),
            'CpuUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.CpuUsage,
                    request_deserializer=gateway__agent__pb2.NullRequest.FromString,
                    response_serializer=gateway__agent__pb2.CpuUsageResponse.SerializeToString,
            ),
            'MemoryUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.MemoryUsage,
                    request_deserializer=gateway__agent__pb2.NullRequest.FromString,
                    response_serializer=gateway__agent__pb2.MemoryUsageResponse.SerializeToString,
            ),
            'ReadLiveLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadLiveLogs,
                    request_deserializer=gateway__agent__pb2.LiveLogsRequest.FromString,
                    response_serializer=gateway__agent__pb2.LiveLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'keyhan.gateway_agent_messages.GatewayAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('keyhan.gateway_agent_messages.GatewayAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Uptime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyhan.gateway_agent_messages.GatewayAgent/Uptime',
            gateway__agent__pb2.NullRequest.SerializeToString,
            gateway__agent__pb2.UptimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CpuUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyhan.gateway_agent_messages.GatewayAgent/CpuUsage',
            gateway__agent__pb2.NullRequest.SerializeToString,
            gateway__agent__pb2.CpuUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MemoryUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyhan.gateway_agent_messages.GatewayAgent/MemoryUsage',
            gateway__agent__pb2.NullRequest.SerializeToString,
            gateway__agent__pb2.MemoryUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadLiveLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/keyhan.gateway_agent_messages.GatewayAgent/ReadLiveLogs',
            gateway__agent__pb2.LiveLogsRequest.SerializeToString,
            gateway__agent__pb2.LiveLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
